import PDFDocument from 'pdfkit';
import type { GenerateStateAgreementInput, GeneratedStateAgreement } from '../state-contract-package';
import type { CaliforniaOfferTermsDocument } from './california-offer-terms.document';
import { CALIFORNIA_STATUTORY_NOTICES as notices } from './california-statutory-notices';
import { NAVSTREET_PDF, drawNavStreetPdfChrome, drawNavStreetSectionBar, registerNavStreetPdfFonts } from '../navstreet-pdf-layout';
const zone='America/Los_Angeles';
const label=(value:string)=>value.replace(/_/g,' ');
const allocation=(value:string)=>value==='split'?'buyer and seller equally':label(value);
const status=(value:string)=>label(value);

const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const yes=(value:boolean|null)=>value===true?'Yes':value===false?'No':'Not selected';
const timestamp=(value:Date|undefined)=>value?new Intl.DateTimeFormat('en-US',{timeZone:zone,year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(value):'Pending';
export async function generateCaliforniaOfferPdf(input:GenerateStateAgreementInput<CaliforniaOfferTermsDocument>):Promise<GeneratedStateAgreement> {
 const t=input.version.terms,p=t.purchase,d=t.deadlines,a=t.disclosures,f=t.sellerFacts;
 const pdf=new PDFDocument({size:'LETTER',bufferPages:true,margins:{top:NAVSTREET_PDF.contentTop,right:NAVSTREET_PDF.margin,bottom:90,left:NAVSTREET_PDF.margin},info:{Title:input.documentTitle,Author:'NavStreet',CreationDate:input.generatedAt}});
 registerNavStreetPdfFonts(pdf);
 const chunks:Buffer[]=[];
 const done=new Promise<Buffer>((resolve,reject)=>{pdf.on('data',chunk=>chunks.push(Buffer.from(chunk)));pdf.on('end',()=>resolve(Buffer.concat(chunks)));pdf.on('error',reject);});
 const room=(height:number)=>{if(pdf.y+height>NAVSTREET_PDF.contentBottom)pdf.addPage();};
 const text=(body:string,size=9.5,color:string=NAVSTREET_PDF.ink)=> {pdf.font('NavStreet-Regular').fontSize(size).fillColor(color).text(body,NAVSTREET_PDF.margin,pdf.y,{width:NAVSTREET_PDF.contentWidth,lineGap:3});pdf.moveDown(.6);};
 const clause=(label:string,body:string)=> {room(72);drawNavStreetSectionBar(pdf,label);text(body);};
 const value=(label:string,v:unknown)=> {room(40);pdf.font('NavStreet-Bold').fontSize(9.5).fillColor(NAVSTREET_PDF.ink).text(label+':',NAVSTREET_PDF.margin,pdf.y,{width:NAVSTREET_PDF.contentWidth});text(String(v ?? 'Not specified'));};
 const signed=[...input.version.buyers,...input.version.sellers].filter(party=>party.requiredSigner);
 const allSigned=signed.length>0&&signed.every(party=>party.signature.status==='signed'&&party.signature.signedAt);
 const effectiveTimes=signed.map(party=>party.signature.signedAt?.toDate()).filter((date):date is Date=>Boolean(date));
 pdf.y=NAVSTREET_PDF.contentTop;
 clause('California residential purchase and sale agreement','An original NavStreet agreement for resale of a house, townhome, planned unit development or condominium. This is not a California Association of REALTORS form. NavStreet provides advertising and software; it is not a broker, attorney, lender, escrow holder or party to this agreement. Each party may obtain independent California legal, tax and transaction advice.');
 value('Version status',allSigned&&input.documentStatus==='approved'?'Final signed version':'Offer version — signatures pending');
 value('Property',[t.property.addressLine1,t.property.addressLine2,t.property.city,'California',t.property.zipCode].filter(Boolean).join(', '));
 value('County / assessor parcel',`${t.property.county || 'Not specified'} / ${t.property.parcelIdentificationNumber || 'Not specified'}`);
 value('Legal description',t.legalDescription.trim() || 'Not provided');
 value('Property type / construction year',`${label(t.property.propertyType)} / ${t.property.yearBuilt ?? 'Not supplied'}`);
 value('Buyer(s)',input.version.buyers.map(party=>party.legalName).join('; '));
 value('Seller(s)',input.version.sellers.map(party=>party.legalName).join('; '));
 clause('1. Sale, price and acceptance',`Seller agrees to convey the described real property and agreed included items to buyer for ${money(p.purchasePriceInCents)}, subject to this version and identified signed attachments. Acceptance requires all required parties to sign the same version and communicate acceptance by electronic delivery authorized below. The effective time is the final required signature recorded and made available to the parties by NavStreet. A proposed counteroffer is a new version and does not bind the parties until accepted. The balance of the price, after deposits and financing, is payable through escrow at closing.`);
 clause('2. Deposits and independent escrow',p.hasEarnestMoney?`Buyer shall deliver ${money(p.earnestMoneyInCents)} to ${p.earnestMoneyHolder || t.settlement.closingAgentName || 'an independent qualified escrow holder jointly selected in writing by the parties'} within ${p.earnestMoneyDueDays} calendar days after acceptance. ${t.conditions.additionalEarnestMoney?`An additional ${money(p.additionalEarnestMoneyInCents)} is due within ${p.additionalEarnestMoneyDueDays} calendar days after acceptance.`:'No additional deposit is agreed.'} Deposits are credited toward the price. Escrow shall hold and disburse deposits according to applicable law and lawful written instructions. These deposits are not automatically forfeited or liquidated damages. NavStreet will not receive or hold transaction funds.`:'No initial or additional escrow deposit is agreed. Buyer remains obligated to provide the purchase funds at closing. The parties will jointly select an independent qualified escrow holder; NavStreet will not hold funds.');
 clause('3. Financing and appraisal',`Funding method: ${label(p.financingType)}. ${p.financingType==='cash'?'Buyer will provide cash funds and has no financing contingency.':`Proposed loan: ${money(p.loanAmountInCents)}, term ${p.loanTermYears} years. Buyer shall diligently seek the loan. Financing contingency: ${yes(t.conditions.financing)}. ${t.conditions.financing?`Buyer shall apply within ${p.loanApplicationDays} calendar days and review loan approval within ${p.loanApprovalDays} calendar days after acceptance. Buyer may cancel in writing while this contingency remains in force if the stated loan cannot be obtained despite diligent good-faith efforts.`:'Buyer bears financing risk without a financing cancellation right.'}`} Appraisal contingency: ${yes(t.conditions.appraisal)}. ${t.conditions.appraisal?`Buyer has ${d.appraisalPeriodDays} calendar days after acceptance to review an appraisal and may cancel in writing while the contingency remains in force if value is below the purchase price.`:'No appraisal cancellation contingency is agreed.'} A cash purchase may still have a separately selected appraisal contingency. Any FHA or VA financing is subject to the applicable lender-required amendatory, escape and certification provisions, included below when applicable; any additional lender-required certifications must be signed and incorporated; the parties shall not require a buyer to waive mandatory program protections. Seller concessions: ${money(p.sellerConcessionsInCents)}, applied only to lawful buyer costs subject to lender limits.`);
 if(p.financingType==='fha')clause('FHA amendatory clause',`It is expressly agreed that notwithstanding any other provisions of this contract, the purchaser shall not be obligated to complete the purchase of the property described herein or to incur any penalty by forfeiture of earnest money deposits or otherwise, unless the purchaser has been given, in accordance with HUD/FHA or VA requirements, a written statement by the Federal Housing Commissioner, Department of Veterans Affairs, or a Direct Endorsement lender setting forth the appraised value of the property of not less than ${money(p.purchasePriceInCents)}. The purchaser shall have the privilege and option of proceeding with consummation of the contract without regard to the amount of the appraised valuation. The appraised valuation is arrived at to determine the maximum mortgage the Department of Housing and Urban Development will insure. HUD does not warrant the value or condition of the property. The purchaser should satisfy himself/herself that the price and condition of the property are acceptable.`);
 if(p.financingType==='va')clause('VA escape clause',`It is expressly agreed that, notwithstanding any other provisions of this contract, the purchaser shall not incur any penalty by forfeiture of earnest money or otherwise be obligated to complete the purchase of the property described herein, if the contract purchase price or cost exceeds the reasonable value of the property established by the Department of Veterans Affairs. The purchaser shall, however, have the privilege and option of proceeding with the consummation of this contract without regard to the amount of the reasonable value established by the Department of Veterans Affairs.`);
 clause('4. Inspection and property condition',`Buyer has ${d.inspectionPeriodDays} calendar days after acceptance to inspect and review the property, title, insurance availability and relevant property records. Buyer may cancel by written notice while this inspection contingency remains in force if the property is unacceptable. Seller shall reasonably permit inspections, subject to lawful occupant rights. Buyer shall not damage the property and shall repair inspection damage. The property is sold in its condition at acceptance, ordinary wear excepted, with no new seller repair obligation unless separately agreed in writing. This does not relieve seller of disclosure duties, agreed maintenance, compliance obligations or liability for fraud or concealment. Buyer may request repairs or credits; a request alone does not modify this agreement or extend a deadline.`);
 clause('5. Written contingency removal and notice to perform',`An inspection, appraisal or financing contingency is removed only by an express written notice signed by buyer and delivered to seller. Expiration of a stated review period alone does not remove it. After an agreed review period expires, seller may give buyer a written notice allowing at least two full calendar days after delivery to remove the outstanding contractual contingency or cancel. If buyer does neither within that notice period, seller may cancel in writing, subject to applicable law, seller performance and lawful disposition of deposits. A notice cannot shorten or waive statutory disclosure termination rights. The parties may extend deadlines only by mutual signed writing. Buyer’s sale-of-other-property contingency: ${yes(t.conditions.saleOfBuyersProperty)}; any selected terms are stated in additional terms below.`);
 clause('6. Included and excluded property',`The transfer includes the real property, existing improvements and installed seller-owned fixtures unless expressly excluded. Additional included personal property: ${t.propertyItems.included || 'None specified'}. Excluded fixtures or personal property: ${t.propertyItems.excluded || 'None specified'}. Leased or third-party equipment and proposed arrangements: ${t.propertyItems.leasedItemsDescription || 'None specified'}. This agreement does not itself bind a lessor or transfer a third-party lease. Any agreed assumption or release requires the relevant written approvals before closing.`);
 clause('7. Title and escrow instructions',`Close of escrow: ${d.settlementDate}. Escrow/title company: ${t.settlement.closingAgentName || 'To be jointly selected by buyer and seller in writing'}. Escrow shall perform only instructions it accepts and is legally authorized to perform. The parties shall provide lawful supplemental escrow instructions consistent with this agreement; inconsistent instructions require a signed amendment. Seller shall provide the preliminary title report at least ${t.settlement.titleEvidenceDaysBeforeClosing} calendar days before closing and convey marketable title by a recordable grant deed, subject to recorded matters accepted by buyer. Seller shall discharge seller liens that must be removed to convey that title. Buyer may object in writing during the inspection review period, or within five calendar days after later delivery of new material title information; seller may cure by closing or seek a mutually signed extension. If seller cannot convey agreed title, buyer may cancel and recover deposits or accept the stated exception in writing. Owner’s title policy paid by ${t.settlement.titlePolicyPayer}; each party pays its own financing charges, seller pays deed preparation and documentary transfer taxes, and ordinary escrow fees are split equally unless additional terms provide otherwise.`);
 clause('8. Prorations, assessments and possession',`Property taxes, periodic association charges and agreed ongoing expenses are prorated as of recording based on available information, with adjustment for later corrected bills when legally required. Pre-closing special assessments are paid by ${allocation(t.settlement.specialAssessmentPayer)}; applicable association transfer fees by ${a.sellerReportsHoa?allocation(t.settlement.hoaTransferFeePayer):'not applicable'}. Seller shall maintain the property until delivery, remove excluded personal property and deliver vacant possession, keys and access devices when the deed records. Seller reports existing leases: ${yes(a.sellerReportsExistingLeases)}. Seller must honor tenant rights. Any continuing tenancy, rent/deposit transfer or seller occupancy requires a separately signed agreement and does not result merely from selecting an offer receipt status.`);
 clause('9. Seller disclosures and actual receipt',`Seller shall promptly deliver applicable statutory disclosures and known material facts, and correct material inaccuracies. TDS: ${status(a.propertyConditionStatus)}; seller applicability: ${f.transferDisclosure}${f.transferDisclosure==='exempt'?'; stated basis: '+f.transferExemptionBasis:''}. NHD: ${status(a.naturalHazardStatus)}; seller applicability: ${f.naturalHazardDisclosure}${f.naturalHazardDisclosure==='exempt'?'; stated basis: '+f.naturalHazardExemptionBasis:''}. Association or condominium records: ${status(a.hoaDocumentsStatus)}; seller reports membership: ${yes(a.sellerReportsHoa)}. Fire-hardening disclosure: ${status(a.fireHardeningStatus)}. Defensible-space documents: ${status(a.defensibleSpaceStatus)}. Recent-resale renovation records: ${status(a.renovationStatus)}. Assisted domestic water tank disclosure: ${status(a.waterTankStatus)}. Agreed seller-document date, if any: ${d.sellerDisclosureDate || 'No separate date'}. Each received selection acknowledges actual buyer receipt and review of the identified uploaded document version. Pending means no receipt acknowledgment. This summary does not replace separately completed statutory statements, signatures or records, and an exemption selection does not establish legal eligibility.`);
 clause('10. Late disclosure and material amendments','Applicable TDS and natural-hazard disclosures must be delivered as soon as practicable before transfer of title. Under Civil Code 1102.3 and 1103.3, delivery of a required disclosure or material amendment after execution of an offer may give buyer three days after personal delivery, five days after mailing, or five days after electronic delivery where electronic transactions are agreed, to terminate by written notice. The applicable statute controls eligibility, commencement and calculation. These rights are separate from contractual inspection deadlines and are not waived by this agreement, a pending answer, a contingency removal or an earlier upload. The parties shall preserve actual delivery and receipt records.');
 clause('11. Wildfire and defensible space',`Refer to the seller’s uploaded hazard disclosures for property-specific fire severity information. Verify current state/local maps and the NHD. For a covered pre-2010 home in a high or very high zone, seller shall provide the Civil Code 1102.6f notice, known listed vulnerable features, current low-cost retrofit list and completed retrofit information, plus applicable inspection information. Seller shall provide applicable defensible-space compliance records under Civil Code 1102.19. ${a.defensibleSpaceStatus==='buyer_agreement'?'If the statutory buyer-agreement route applies because seller lacks the required documentation, buyer agrees to obtain documentation in accordance with the applicable local ordinance or, where there is no such ordinance and an eligible inspection/documentation service is available, within one year after close of escrow as specified in Civil Code 1102.19(b). This agreement does not suspend enforceable maintenance requirements.':'No buyer assumption of defensible-space documentation is elected here; the parties must deliver required documentation or separately agree to a lawful statutory route when applicable.'}`);
 clause('12. Renovations and property-specific records',`Refer to the seller’s uploaded renovation disclosures for property-specific records. For an applicable single-family transfer under Civil Code 1102.6h, seller shall disclose covered contractor work, required contractor identity/contact information, and permits or statutorily permitted third-party permit-source information. Confirm the 18-month calculation at acceptance. Refer to the seller’s uploaded water tank disclosure when applicable. Where Civil Code 1102.156 applies, seller shall provide its statutory statement, including possible nonconveyance and advice to investigate water availability. Seller shall provide applicable special tax/Mello-Roos, private-transfer-fee, local, lease and known-condition disclosures. Seller’s known state/local restrictions on future replacement of included gas appliances under Civil Code 1102.6j: ${f.gasApplianceRestrictions || 'Refer to the seller’s uploaded disclosures when applicable.'}`);
 clause('13. Association and condominium records','For property in a common-interest development, seller shall supply the applicable Civil Code 4525 resale documents, including current governing, financial, assessment, rental restriction, violation and applicable elevated-element inspection information. Buyer may review these under the contractual inspection contingency and any applicable statutory rights. A pending status does not acknowledge receipt. Obtain documents early; NavStreet does not guarantee completeness or association response time.');
 clause('14. Safety, earthquake and local requirements','Seller and buyer shall comply with applicable smoke alarm, carbon monoxide, water-heater bracing, water-conserving plumbing and local point-of-sale obligations. Seller shall deliver the applicable earthquake safety guide and required residential earthquake risk disclosure for covered older construction, plus applicable existing reports. A general environmental booklet is useful information and does not replace disclosure of known property-specific conditions. The parties shall resolve any agreed compliance work and allocation in signed instructions before closing. A new radon, pest, electrical or other report is not automatically required by this agreement merely to list the property.');
 clause('15. Federal lead disclosure and inspection opportunity',`Lead packet status: ${status(a.leadPaintStatus)}. ${a.leadPaintStatus==='exempt'?'Stated federal exemption: '+a.leadExemptionBasis+'.':''} For applicable target housing, the separately signed lead disclosure, available records and EPA pamphlet must be delivered before buyer becomes obligated under the purchase contract. Buyer inspection choice: ${a.leadPaintStatus==='received'?(a.leadInspectionSelection==='waived'?'buyer expressly waives the inspection opportunity':(a.leadInspectionSelection==='ten_days'?'10':String(a.leadInspectionDays))+' calendar days after acceptance'):'not selected for target housing'}. Unless waived, buyer may cancel in writing during that agreed lead review period if a lead inspection or assessment is unacceptable. The opportunity does not require a new seller test. The separately signed disclosure packet is incorporated and retained with this version.`);
 if(a.leadPaintStatus==='received')clause('Federal lead warning statement',notices.lead);
 clause('16. Electrical system inspection advice — Civil Code 1102.6i',notices.electrical);
 clause('17. Appraisal nondiscrimination — Civil Code 1102.6g',notices.appraisal);
 clause('18. Megan’s Law notice — Civil Code 2079.10a',notices.megansLaw);
 room(250);pdf.font('NavStreet-Bold').fontSize(14).fillColor('#8b0000').text("Notice of Your 'Supplemental' Property Tax Bill.",NAVSTREET_PDF.margin,pdf.y,{width:NAVSTREET_PDF.contentWidth});pdf.moveDown(.4);text(notices.supplementalTax,12,'#8b0000');
 clause('19. Final verification and casualty','Buyer may conduct a final inspection reasonably close to closing to confirm agreed condition and completion of agreed work; this is not a new inspection contingency. Seller bears the risk of material casualty before recording, except loss caused by buyer. If material damage or a material taking occurs before closing, buyer may cancel by written notice before recording and recover deposits, or the parties may agree in writing to proceed with an appropriate allocation or adjustment, subject to California law.');
 clause('20. Default and deposit disputes','On a material breach, a nonbreaching party may exercise lawful remedies under California law, including appropriate damages, specific performance or cancellation. Seller has no automatic right to retain a deposit. Escrow shall disburse disputed deposits only on lawful joint written instructions, a final enforceable adjudication or another process authorized by applicable law. This agreement contains no liquidated-damages election and no compulsory arbitration agreement. Any later election requires a separately executed compliant agreement and any statutory special signature and typography requirements.');
 clause('21. Notices, signature delivery and expiration',`The parties consent to electronic delivery and electronic signatures: ${yes(t.delivery.electronicDeliveryAuthorized)}. Notices shall be sent to the parties’ stated contact addresses with retained delivery records; a statutory termination may also use any lawful delivery method. This offer expires at ${timestamp(new Date(t.delivery.expiresAt))} unless accepted before that instant. Calendar-day periods begin the day after acceptance; stated contract dates end at 11:59 p.m. Pacific time. Statutory time computation controls statutory rights. Changes require a signed written amendment or counteroffer version, and signatures do not transfer between versions.`);
 clause('22. Additional terms',t.additionalTerms || 'None.');
 clause('23. Entire agreement and independent advice','This version and expressly incorporated signed attachments state the agreement between buyer and seller. Each signer represents authority to sign for the stated capacity. Brokerage representation, if any, requires the broker’s separate lawful disclosures and agreements; NavStreet is not an agent and no commission is created by this agreement. Seller and buyer shall obtain appropriate escrow, tax and legal assistance concerning FIRPTA, California withholding, special transactions, foreclosure-related protections and required supplements. No term overrides nonwaivable statutory protections.');
 room(110);drawNavStreetSectionBar(pdf,'Buyer acknowledgments and reviewed documents');
 text('The following answers and document identifiers are retained with this exact offer version. A pending answer does not acknowledge delivery. A document identifier identifies the reviewed upload; it does not by itself establish that a document is complete or separately signed.');
 value('Seller lease statement reviewed and acknowledged',yes(a.leaseStatementAcknowledged));
 value('California statutory notices and gas-appliance information read',yes(a.californiaNoticesAcknowledged));
 value('Electronic delivery and offer signatures authorized',yes(t.delivery.electronicDeliveryAuthorized));
 value('Contract time zone',t.delivery.timeZone);
 const receiptDocuments:ReadonlyArray<readonly [string,string,string]>=[
  ['california-transfer-disclosure','Transfer Disclosure Statement',a.propertyConditionStatus],
  ['california-natural-hazard-disclosure','Natural Hazard Disclosure',a.naturalHazardStatus],
  ['california-fire-hardening','Fire-hardening disclosure',a.fireHardeningStatus],
  ['california-defensible-space','Defensible-space documents',a.defensibleSpaceStatus],
  ['california-recent-renovations','Recent-resale renovation disclosure',a.renovationStatus],
  ['california-assisted-water-tank','Assisted domestic water tank disclosure',a.waterTankStatus],
  ['california-association-documents','Association or condominium records',a.hoaDocumentsStatus],
  ['lead-based-paint','Federal lead packet',a.leadPaintStatus],
 ];
 for(const [key,title,receiptStatus] of receiptDocuments) {
  value(title,`${status(receiptStatus)}${receiptStatus==='received'?`; reviewed document version: ${t.documentVersions[key] || 'Not recorded — receipt must be checked before submission'}`:''}`);
 }
 const namedDocumentKeys=new Set(receiptDocuments.map(([key])=>key));
 for(const [key,version] of Object.entries(t.documentVersions)) {
  if(!namedDocumentKeys.has(key))value(`Additional reviewed document (${label(key)})`,version);
 }
 pdf.addPage();drawNavStreetSectionBar(pdf,'Version signature record');
 value('Offer / version',`${input.offer.referenceNumber} / ${input.version.versionNumber}`);
 value('Version created',timestamp(input.version.createdAt?.toDate()));
 value('Electronic delivery and offer signatures authorized',yes(t.delivery.electronicDeliveryAuthorized));
 const compactValue=(label:string,v:unknown)=>{room(30);pdf.font('NavStreet-Regular').fontSize(9.5).fillColor(NAVSTREET_PDF.ink).text(`${label}: ${v ?? 'Not supplied'}`,NAVSTREET_PDF.margin,pdf.y,{width:NAVSTREET_PDF.contentWidth,lineGap:2});pdf.moveDown(.4);};
 for(const [role,parties] of [['Buyer',input.version.buyers],['Seller',input.version.sellers]] as const) for(const party of parties) {
  room(230);value(role,party.legalName);
  compactValue('Signing capacity',label(party.capacity || 'individual'));
  compactValue('Email / phone',`${party.email} / ${party.phone || 'Not supplied'}`);
  if(party.mailingAddress) {
   const address=party.mailingAddress;
   compactValue('Mailing address',[address.addressLine1,address.addressLine2,address.city,address.state,address.zipCode,address.country].filter(Boolean).join(', '));
  }
  if(role==='Buyer') {
   if(party.proposedDeedName)compactValue('Proposed deed name',party.proposedDeedName);
   if(party.intendedUse)compactValue('Intended use',label(party.intendedUse));
  }
  compactValue('Required signer',party.requiredSigner?'Yes':'No');
  compactValue('Electronic signature',party.signature.status==='signed'&&party.signature.signedAt?'/s/ '+party.legalName:'Awaiting signature');
  compactValue('Signature time — Pacific',timestamp(party.signature.signedAt?.toDate()));
 }
 if(allSigned&&effectiveTimes.length)value('Final required signature time — Pacific',timestamp(new Date(Math.max(...effectiveTimes.map(date=>date.getTime())))));
 const pageCount=pdf.bufferedPageRange().count;
 for(let index=0;index<pageCount;index++){pdf.switchToPage(index);const bottomMargin=pdf.page.margins.bottom;pdf.page.margins.bottom=0;drawNavStreetPdfChrome(pdf,{stateName:'California',referenceNumber:input.offer.referenceNumber,versionNumber:input.version.versionNumber,pageNumber:index+1,pageCount});pdf.page.margins.bottom=bottomMargin;}
 pdf.end();return {buffer:await done,fileName:`NavStreet-CA-${input.offer.referenceNumber}-v${input.version.versionNumber}.pdf`,pageCount};
}
