import { validateSubmissionParties } from '../submission-parties';
import { requireValue, money, date } from '../submission-values';
import type { ValidateStateSubmissionInput } from '../state-contract-package';
import type { UtahOfferTermsDocument } from './utah-offer-terms.document';
export function validateUtahSubmission(input: ValidateStateSubmissionInput<UtahOfferTermsDocument>): void {
  const { offer, version } = input; const t = version.terms; const p = t.purchase; const d = t.deadlines;
  requireValue(offer.stateCode === 'UT' && version.stateCode === 'UT' && t.stateCode === 'UT', 'The offer must belong to Utah.');
  requireValue(offer.currentVersionUid === version.Uid && version.offerUid === offer.Uid && version.status === 'draft' && version.immutable === false, 'Only the current mutable version can be submitted.');
  requireValue(t.contractType === 'navstreet_utah_residential_sale_2026' && t.property.listingUid === offer.listingUid && t.property.state === 'UT', 'The contract or property snapshot is invalid.');
  validateSubmissionParties(version);
  requireValue(t.property.addressLine1?.trim() && t.property.city?.trim() && t.property.zipCode?.trim() && t.property.county?.trim(), 'The listing must identify the Utah property by street address, city, ZIP code, and county.');
  requireValue(money(p.purchasePriceInCents, true) && money(p.earnestMoneyInCents, true) && p.earnestMoneyHolder.trim(), 'Purchase price, earnest money and escrow holder are required.');
  requireValue(Number.isSafeInteger(p.earnestMoneyDueDays) && p.earnestMoneyDueDays >= 1 && p.earnestMoneyDueDays <= 30, 'Earnest money is due within 1 to 30 days.');
  requireValue(p.financingType !== 'unselected' && ['cash','conventional','fha','va','usda'].includes(p.financingType), 'Choose cash or financing.');
  requireValue(p.financingType === 'cash' || (money(p.loanAmountInCents, true) && p.loanAmountInCents <= p.purchasePriceInCents), 'Enter a valid loan amount.');
  requireValue(money(p.sellerConcessionsInCents) && p.sellerConcessionsInCents <= p.purchasePriceInCents, 'Enter valid seller concessions.');
  requireValue(!t.conditions.additionalEarnestMoney || money(p.additionalEarnestMoneyInCents, true), 'Enter the additional earnest money.');
  requireValue(t.propertyItems.waterRightsIncluded !== null, 'Specify whether water rights are included.');
  for (const k of ['dueDiligence','appraisal','financing','saleOfBuyersProperty','additionalEarnestMoney'] as const) requireValue(typeof t.conditions[k] === 'boolean', `Select the ${k} condition.`);
  requireValue(p.financingType !== 'cash' || t.conditions.financing === false, 'Cash offers cannot have a financing condition.');
  requireValue(date(d.sellerDisclosureDate) && date(d.settlementDate) && d.sellerDisclosureDate <= d.settlementDate, 'Disclosure and settlement deadlines must be valid and ordered.');
  requireValue(!t.conditions.dueDiligence || date(d.dueDiligenceDate), 'Set a due diligence deadline.');
  requireValue(!(t.conditions.appraisal || t.conditions.financing) || date(d.financingAppraisalDate), 'Set a financing and appraisal deadline.');
  requireValue(t.settlement.possession !== 'unselected' && t.settlement.specialAssessmentPayer !== 'unselected' && t.settlement.hoaTransferFeePayer !== 'unselected', 'Complete possession and costs.');
  requireValue(t.settlement.possession === 'at_recording' || (Number.isSafeInteger(t.settlement.possessionDelay) && t.settlement.possessionDelay >= 1 && t.settlement.possessionDelay <= 365), 'Enter the possession delay.');
  requireValue(t.disclosures.propertyConditionStatus !== 'unselected' && t.disclosures.hoaDocumentsStatus !== 'unselected', 'Select disclosure and association status.');
  requireValue(t.disclosures.leadPaintStatus !== 'unselected', 'Select lead paint status.');
  requireValue(t.property.yearBuilt == null || t.property.yearBuilt >= 1978 || ['received','exempt'].includes(t.disclosures.leadPaintStatus), 'The pre-1978 lead packet or exemption is required before signing.');
  requireValue(typeof t.disclosures.sellerReportsCurrentMethContamination === 'boolean', 'Seller must state whether current contamination is known.');
  requireValue(!t.conditions.saleOfBuyersProperty || t.additionalTerms.trim(), 'This purchase is conditioned on selling another property owned by the buyer. Describe that condition in additional terms, or correct the purchase-condition answer.');
  requireValue(t.disclosures.leadPaintStatus !== 'received' || t.disclosures.leadInspectionSelection !== 'unselected', 'Choose the federal lead inspection opportunity.');
  requireValue(t.disclosures.leadInspectionSelection !== 'other_period' || (Number.isSafeInteger(t.disclosures.leadInspectionDays) && t.disclosures.leadInspectionDays >= 1 && t.disclosures.leadInspectionDays <= 60), 'Enter 1 to 60 agreed lead inspection days.');
  requireValue(t.disclosures.methamphetamineContaminationAcknowledged === true, 'Review the methamphetamine statement.');
  requireValue(t.delivery.timeZone === 'America/Denver' && t.delivery.electronicDeliveryAuthorized === true, 'Electronic delivery consent and Mountain time are required.');
  const expiration = new Date(t.delivery.expiresAt);
  requireValue(Number.isFinite(expiration.getTime()) && expiration.getTime() > Date.now() && version.expiresAt === t.delivery.expiresAt, 'Enter a future offer expiration matching the version.');
}
