import PDFDocument from 'pdfkit';
import type { GenerateStateAgreementInput, GeneratedStateAgreement } from '../state-contract-package';
import type { SouthCarolinaOfferTermsDocument } from './south-carolina-offer-terms.document';
import { SOUTH_CAROLINA_STATUTORY_NOTICES as notices } from './south-carolina-statutory-notices';
import { NAVSTREET_PDF, drawNavStreetPdfChrome, drawNavStreetSectionBar, registerNavStreetPdfFonts } from '../navstreet-pdf-layout';
const zone='America/New_York';
const label=(value:string)=>value.replace(/_/g,' ');
const allocation=(value:string)=>value==='split'?'buyer and seller equally':label(value);
const status=(value:string)=>label(value);

const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const yes=(value:boolean|null)=>value===true?'Yes':value===false?'No':'Not selected';
const timestamp=(value:Date|undefined)=>value?new Intl.DateTimeFormat('en-US',{timeZone:zone,year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(value):'Pending';
export async function generateSouthCarolinaOfferPdf(input:GenerateStateAgreementInput<SouthCarolinaOfferTermsDocument>):Promise<GeneratedStateAgreement> {
 const t=input.version.terms,p=t.purchase,d=t.deadlines,a=t.disclosures;
 const pdf=new PDFDocument({size:'LETTER',bufferPages:true,margins:{top:NAVSTREET_PDF.contentTop,right:NAVSTREET_PDF.margin,bottom:90,left:NAVSTREET_PDF.margin},info:{Title:input.documentTitle,Author:'NavStreet',CreationDate:input.generatedAt}});
 registerNavStreetPdfFonts(pdf);
 const chunks:Buffer[]=[];
 const done=new Promise<Buffer>((resolve,reject)=>{pdf.on('data',chunk=>chunks.push(Buffer.from(chunk)));pdf.on('end',()=>resolve(Buffer.concat(chunks)));pdf.on('error',reject);});
 const room=(height:number)=>{if(pdf.y+height>NAVSTREET_PDF.contentBottom)pdf.addPage();};
 const text=(body:string,size=9.5,color:string=NAVSTREET_PDF.ink)=> {pdf.font('NavStreet-Regular').fontSize(size).fillColor(color).text(body,NAVSTREET_PDF.margin,pdf.y,{width:NAVSTREET_PDF.contentWidth,lineGap:3});pdf.moveDown(.6);};
 const clause=(label:string,body:string)=> {room(72);drawNavStreetSectionBar(pdf,label);text(body);};
 const value=(label:string,v:unknown)=> {room(40);pdf.font('NavStreet-Bold').fontSize(9.5).fillColor(NAVSTREET_PDF.ink).text(label+':',NAVSTREET_PDF.margin,pdf.y,{width:NAVSTREET_PDF.contentWidth});text(String(v ?? 'Not specified'));};
 const signed=[...input.version.buyers,...input.version.sellers].filter(party=>party.requiredSigner);
 const allSigned=signed.length>0&&signed.every(party=>party.signature.status==='signed'&&party.signature.signedAt);
 const effectiveTimes=signed.map(party=>party.signature.signedAt?.toDate()).filter((date):date is Date=>Boolean(date));
 pdf.y=NAVSTREET_PDF.contentTop;

 clause('South Carolina residential purchase and sale agreement','Original NavStreet agreement for resale of a house, townhome, planned unit development or condominium. This is not a South Carolina REALTORS form or a government-approved purchase agreement. NavStreet provides advertising and software and is not an agent, closing attorney, escrow holder or party. Each party should obtain independent South Carolina legal and tax advice. This agreement does not cover vacant land, manufactured homes, multiple-unit properties, installment sales or timeshares.');
 value('Version status',allSigned&&input.documentStatus==='approved'?'Final signed version':'Offer version — signatures pending');
 value('Property',[t.property.addressLine1,t.property.addressLine2,t.property.city,'South Carolina',t.property.zipCode].filter(Boolean).join(', '));
 value('County / parcel',`${t.property.county || 'Not specified'} / ${t.property.parcelIdentificationNumber || 'Not specified'}`);
 value('Seller-provided legal description',t.legalDescription.trim() || 'Not provided; the closing attorney must confirm the property description for conveyance.');
 value('Property type / construction year',`${label(t.property.propertyType)} / ${t.property.yearBuilt ?? 'Not supplied'}`);
 value('Buyer(s)',input.version.buyers.map(party=>party.legalName).join('; '));
 value('Seller(s)',input.version.sellers.map(party=>party.legalName).join('; '));
 clause('1. Sale, price and acceptance',`Seller agrees to sell and buyer agrees to purchase the identified real property and included items for ${money(p.purchasePriceInCents)}, subject to this version and expressly incorporated attachments. Acceptance requires all required parties to sign this exact version and deliver acceptance through the authorized electronic process before offer expiration. The effective time is the final required signature recorded and made available to the parties. A counteroffer is a new proposed version and binds neither party until accepted. The balance after deposits and loan proceeds is due through the independent closing attorney at closing.`);
 clause('2. Earnest money and independent holder',p.hasEarnestMoney?`Buyer shall deliver ${money(p.earnestMoneyInCents)} within ${p.earnestMoneyDueDays} calendar days after acceptance to ${p.earnestMoneyHolder || t.settlement.closingAgentName || 'the licensed South Carolina closing attorney or other lawful independent holder selected by the parties'}. ${t.conditions.additionalEarnestMoney?`An additional ${money(p.additionalEarnestMoneyInCents)} is due within ${p.additionalEarnestMoneyDueDays} calendar days after acceptance.`:'No additional deposit is agreed.'} Deposits credit toward the price. Holder must accept lawful written escrow instructions. No deposit is automatically forfeited, and NavStreet will not hold transaction funds.`:'No earnest money deposit is agreed. Buyer remains obligated to fund closing. NavStreet will not receive or hold transaction funds.');
 clause('3. Financing, appraisal and concessions',`Funding: ${label(p.financingType)}. ${p.financingType==='cash'?'Buyer will provide cash and has no financing contingency.':`Proposed loan ${money(p.loanAmountInCents)}, term ${p.loanTermYears} years. Financing contingency: ${yes(t.conditions.financing)}. ${t.conditions.financing?`Buyer shall apply within ${p.loanApplicationDays} calendar days after acceptance and may terminate by written notice delivered within ${p.loanApprovalDays} calendar days after acceptance if the proposed loan cannot be obtained despite diligent good-faith efforts.`:'Buyer bears financing risk without a contractual financing cancellation right.'}`} Appraisal contingency: ${yes(t.conditions.appraisal)}. ${t.conditions.appraisal?`Buyer may terminate by written notice within ${d.appraisalPeriodDays} calendar days after acceptance if an appraisal is below the purchase price.`:'No contractual appraisal contingency is selected.'} FHA and VA mandatory protections below control despite any contrary election. Seller concessions: ${money(p.sellerConcessionsInCents)}, limited to lawful buyer costs and lender requirements.`);
 if(p.financingType==='fha')clause('FHA amendatory clause',`It is expressly agreed that notwithstanding any other provisions of this contract, the purchaser shall not be obligated to complete the purchase of the property described herein or to incur any penalty by forfeiture of earnest money deposits or otherwise, unless the purchaser has been given, in accordance with HUD/FHA or VA requirements, a written statement by the Federal Housing Commissioner, Department of Veterans Affairs, or a Direct Endorsement lender setting forth the appraised value of the property of not less than ${money(p.purchasePriceInCents)}. The purchaser shall have the privilege and option of proceeding with consummation of the contract without regard to the amount of the appraised valuation. The appraised valuation is arrived at to determine the maximum mortgage the Department of Housing and Urban Development will insure. HUD does not warrant the value or condition of the property. The purchaser should satisfy himself/herself that the price and condition of the property are acceptable.`);
 if(p.financingType==='va')clause('VA escape clause',`It is expressly agreed that, notwithstanding any other provisions of this contract, the purchaser shall not incur any penalty by forfeiture of earnest money or otherwise be obligated to complete the purchase of the property described herein, if the contract purchase price or cost exceeds the reasonable value of the property established by the Department of Veterans Affairs. The purchaser shall, however, have the privilege and option of proceeding with the consummation of this contract without regard to the amount of the reasonable value established by the Department of Veterans Affairs.`);
 clause('4. Inspection and condition',`Buyer has ${d.inspectionPeriodDays} calendar days after acceptance to inspect the property, pest and wood-destroying organism conditions, title, insurance availability, flood risks, utilities, association restrictions and related records. Buyer may terminate by written notice delivered within that period if the property is unacceptable, with return of deposits subject to lawful escrow procedures. Seller shall reasonably permit inspections subject to occupant rights. Buyer shall repair damage caused by inspections. Seller must maintain the property in substantially its condition at acceptance through closing, ordinary wear excepted. A repair or credit request alone does not amend the agreement or extend a deadline. No seller repair obligation arises unless agreed in writing; disclosure duties and fraud remedies are preserved.`);
 clause('5. Contract deadlines and other-property contingency',`The inspection, appraisal and financing cancellation periods above are negotiated contract terms. Buyer must deliver an applicable cancellation notice before the stated period ends. After that deadline the contractual cancellation right expires unless extended by mutual signed writing; nonwaivable statutory rights and the FHA/VA protections remain. Buyer’s sale-of-other-property contingency: ${yes(t.conditions.saleOfBuyersProperty)}. If selected, the property, sale deadline and agreed cancellation terms are in additional terms. Day counts begin on the day after acceptance and end at 11:59 p.m. Eastern time unless a statutory rule controls.`);
 clause('6. Fixtures, personal property and leases',`Seller-owned installed fixtures and improvements convey unless expressly excluded. Additional included items: ${t.propertyItems.included || 'None specified'}. Excluded items: ${t.propertyItems.excluded || 'None specified'}. Leased or third-party equipment and arrangements: ${t.propertyItems.leasedItemsDescription || 'None specified'}. A third-party lease is not transferred without required approvals. Seller reports existing leases: ${yes(a.sellerReportsExistingLeases)}. Tenant rights and existing contractual obligations survive as required by law. Any permitted continuing tenancy or seller occupancy requires expressly agreed written terms.`);
 clause('7. Closing attorney, title and conveyance',`Closing date: ${d.settlementDate}. South Carolina closing attorney: ${t.settlement.closingAgentName || 'To be selected by the parties before closing'}. ${notices.closing} Seller shall provide available title evidence at least ${t.settlement.titleEvidenceDaysBeforeClosing} calendar days before closing. Seller shall convey marketable, insurable fee-simple title by a duly executed deed acceptable to buyer and the closing attorney, free of monetary liens other than obligations expressly assumed in writing, subject to permitted recorded covenants, easements and restrictions. Seller pays to release seller’s monetary liens. Buyer shall notify seller promptly of material title objections; seller shall have until closing to cure. If a material defect remains uncured at closing, buyer may terminate with deposits returned or elect in writing to accept the title defect. No party is required to accept an uninsured title defect.`);
 clause('8. Costs, prorations and assessments',`Buyer pays buyer’s loan charges and lender title insurance. Seller pays costs to release seller’s liens, seller’s deed preparation and applicable deed recording or transfer taxes. Owner title policy: ${allocation(t.settlement.titlePolicyPayer)}. Assessments levied before closing: ${allocation(t.settlement.specialAssessmentPayer)}. Applicable association transfer fees: ${a.sellerReportsHoa?allocation(t.settlement.hoaTransferFeePayer):'not applicable'}. Each party pays its own legal advice; buyer pays the closing attorney’s ordinary settlement charge unless a different allocation is agreed below. Property taxes, association dues, rent and recurring property charges prorate through closing using available information, with adjustment when accurate bills become available. No fee or commission to NavStreet is created by this agreement.`);
 clause('9. Possession and final inspection','Buyer receives possession upon completed closing, lawful recording and authorized disbursement, subject only to expressly incorporated lawful continuing occupancy terms. Seller shall remove excluded personal property and debris and deliver available keys and access devices. Buyer may inspect shortly before closing to confirm agreed condition and performance; that inspection does not renew expired contingencies. Seller occupancy after closing requires a separately signed agreement. Vacation rental rights below control where applicable.');
 clause('10. Property condition statement and agreed delivery',`${notices.condition} Selected status: ${status(a.propertyConditionStatus)}. ${a.propertyConditionStatus==='pending'?`Under S.C. Code 27-50-50(A), both parties expressly agree seller shall deliver the completed and signed official statement to buyer no later than ${d.sellerDisclosureDate}, instead of delivery before signing. This is an agreed delivery time and does not waive seller’s duty to disclose known material facts or promptly correct material inaccuracies.`:a.propertyConditionStatus==='waived'?'Under S.C. Code 27-50-30(13), buyer and seller, by signing this version, expressly agree in writing not to complete the statutory condition statement. This mutual agreement does not waive fraud remedies, independent nonwaivable duties or federal lead requirements.':a.propertyConditionStatus==='exempt'?`Claimed statutory exemption and supporting facts: ${a.propertyExemptionBasis}. The parties must confirm that the stated transfer actually qualifies; a no-representation answer is not an exemption.`:'Buyer states the uploaded condition statement was received and reviewed; seller remains responsible for its completeness, signature and required corrections.'} Neither a missing upload nor a pending selection establishes receipt.`);
 clause('11. Associations and property-specific records',`Seller reports association membership: ${yes(a.sellerReportsHoa)}. Association document status: ${status(a.hoaDocumentsStatus)}. When applicable, seller shall provide available recorded restrictions, governing documents, dues, assessments and transfer requirements ${d.sellerDisclosureDate?'by '+d.sellerDisclosureDate:'promptly before closing'}. Buyer remains responsible for evaluating restrictions and charges during the agreed review period. The condition statement includes required HOA information; uploading it does not substitute for separate property-specific records or lender requirements.`);
 clause('12. Applicable beachfront disclosure',a.coastalApplies?`Seller and buyer identify the property as wholly or partly seaward of a beachfront setback or jurisdictional line and acknowledge that the property is or may be affected by the setback line and baseline under S.C. Code 48-39-330. Baseline location/source: ${a.coastalBaselineDescription}. Setback or jurisdictional line: ${a.coastalSetbackDescription}. Seaward corners of all habitable structures, referenced to SC State Plane NAD-1983: ${a.coastalStructureCoordinates}. Latest departmental local erosion rate, zone and source date: ${a.coastalErosionRate}. These seller-provided details form part of this contract. Obtain survey and current departmental records to verify them; signing does not certify regulatory accuracy.`:'Based on the seller’s information, the parties identify no property wholly or partly seaward of a beachfront setback or jurisdictional line. If that information is incorrect, the required property-specific disclosure must be included by signed amendment; this selection does not create an exemption from coastal law.');
 clause('13. Existing vacation rentals',a.vacationRentalsApply?`${notices.rentals} Seller’s written disclosure of ALL future rental periods and arrangements, incorporated into this version before ratification: ${a.vacationRentalPeriods}. Buyer shall honor vacation rental and applicable management agreements for periods beginning no later than 90 days after buyer’s interest is recorded, as required by S.C. Code 27-50-250. For later periods, enforceability and tenant refunds follow the statute, including the applicable 45-day refund deadline. Seller shall provide the rental manager buyer’s name and address within the statutory 14-day period after contract or transfer, whichever is earlier, and the required transfer/recording information within 14 days after transfer. The closing attorney shall address advance rent, deposits, notices and occupancy obligations.`:'Seller’s information identifies no existing future vacation rental bookings. Seller must disclose any actual bookings in writing before ratification; ordinary tenancy and other occupancy rights remain protected.');
 clause('14. Federal lead materials',`Lead status: ${status(a.leadPaintStatus)}. ${a.leadPaintStatus==='exempt'?`Claimed federal exemption and facts: ${a.leadExemptionBasis}.`:''} For covered pre-1978 housing, seller shall provide the required lead warning statement, known lead disclosures, available records and EPA pamphlet before buyer signs, with the required separate signed lead disclosure. An inspection waiver does not waive those materials. ${a.leadPaintStatus==='received'?`Buyer reports receipt and selects ${a.leadInspectionSelection==='waived'?'a written waiver of the lead inspection opportunity':(a.leadInspectionSelection==='ten_days'?'10':a.leadInspectionDays)+' calendar days after acceptance for a lead inspection/risk assessment'}. ${a.leadInspectionSelection!=='waived'?'Buyer may terminate by written notice within that lead inspection period if the lead findings are unacceptable, with return of deposits subject to lawful escrow procedures.':''}`:'No inspection selection overrides a nonwaivable federal disclosure duty.'} This purchase agreement does not replace the separately required lead disclosure signatures.`);
 clause('15. Casualty, condemnation and default','If a material casualty or condemnation affects the property before closing, seller shall notify buyer promptly. Buyer may terminate before closing and recover deposits or proceed under a signed allocation of proceeds or adjustment consistent with law. A nonbreaching party may exercise lawful South Carolina remedies for material breach, including damages, specific performance or cancellation where available. There is no automatic forfeiture, liquidated-damages election or compulsory arbitration in this agreement. Disputed escrow funds may be disbursed only through lawful joint instructions, an enforceable adjudication or other process authorized by law.');
 clause('16. Notices, signatures and expiration',`Electronic delivery and signatures authorized: ${yes(t.delivery.electronicDeliveryAuthorized)}. Notices shall be sent to the stated party contact addresses using a method that retains delivery evidence; statutory notice methods remain available. The offer expires at ${timestamp(new Date(t.delivery.expiresAt))}. No signature transfers to a new version. Changes and extensions require mutual signed writing. Counteroffer and superseded versions remain in history but are not the accepted agreement.`);
 clause('17. Additional terms',t.additionalTerms || 'None.');
 clause('18. Entire agreement and independent assistance','This exact version and expressly incorporated attachments contain the parties’ agreement. Each signer confirms authority in the stated capacity. No brokerage relationship or commission is created. The parties obtain their own legal, tax, title, inspection and financing assistance, including applicable FIRPTA or South Carolina nonresident withholding, local requirements and transaction-specific addenda. Nonwaivable laws control conflicting terms. A supporting document identifier alone does not incorporate inconsistent terms or certify completeness.');
 room(110);drawNavStreetSectionBar(pdf,'Buyer receipt and document version record');
 text('A pending answer is not acknowledgment of delivery. Received selections record the particular reviewed upload. Seller remains responsible for required separate disclosure signatures and completeness.');
 value('Lease statement acknowledged',yes(a.leaseStatementAcknowledged));
 value('South Carolina information reviewed',yes(a.southCarolinaNoticesAcknowledged));
 for(const [key,title,receiptStatus] of [
  ['south-carolina-property-condition','Property condition statement',a.propertyConditionStatus],
  ['south-carolina-association-documents','Association documents',a.hoaDocumentsStatus],
  ['lead-based-paint','Federal lead packet',a.leadPaintStatus],
 ]) value(title,`${status(receiptStatus)}${receiptStatus==='received'?'; reviewed document version: '+(t.documentVersions[key] || 'Not recorded'):''}`);
 for(const key of ['south-carolina-coastal-disclosure','south-carolina-vacation-rentals']) if(t.documentVersions[key]) value('Available supporting upload: '+label(key),t.documentVersions[key]);
 room(400);drawNavStreetSectionBar(pdf,'Version signature record');
 value('Offer / version',`${input.offer.referenceNumber} / ${input.version.versionNumber}`);
 value('Version created',timestamp(input.version.createdAt?.toDate()));
 value('Electronic delivery and offer signatures authorized',yes(t.delivery.electronicDeliveryAuthorized));
 const compactValue=(label:string,v:unknown)=>{room(30);pdf.font('NavStreet-Regular').fontSize(9.5).fillColor(NAVSTREET_PDF.ink).text(`${label}: ${v ?? 'Not supplied'}`,NAVSTREET_PDF.margin,pdf.y,{width:NAVSTREET_PDF.contentWidth,lineGap:2});pdf.moveDown(.4);};
 for(const [role,parties] of [['Buyer',input.version.buyers],['Seller',input.version.sellers]] as const) for(const party of parties) {
  room(230);value(role,party.legalName);
  compactValue('Signing capacity',label(party.capacity || 'individual'));
  compactValue('Email / phone',`${party.email} / ${party.phone || 'Not supplied'}`);
  if(party.mailingAddress) {
   const address=party.mailingAddress;
   compactValue('Mailing address',[address.addressLine1,address.addressLine2,address.city,address.state,address.zipCode,address.country].filter(Boolean).join(', '));
  }
  if(role==='Buyer') {
   if(party.proposedDeedName)compactValue('Proposed deed name',party.proposedDeedName);
   if(party.intendedUse)compactValue('Intended use',label(party.intendedUse));
  }
  compactValue('Required signer',party.requiredSigner?'Yes':'No');
  compactValue('Electronic signature',party.signature.status==='signed'&&party.signature.signedAt?'/s/ '+party.legalName:'Awaiting signature');
  compactValue('Signature time — Eastern',timestamp(party.signature.signedAt?.toDate()));
 }
 if(allSigned&&effectiveTimes.length)value('Final required signature time — Eastern',timestamp(new Date(Math.max(...effectiveTimes.map(date=>date.getTime())))));
 const pageCount=pdf.bufferedPageRange().count;
 for(let index=0;index<pageCount;index++){pdf.switchToPage(index);const bottomMargin=pdf.page.margins.bottom;pdf.page.margins.bottom=0;drawNavStreetPdfChrome(pdf,{stateName:'South Carolina',referenceNumber:input.offer.referenceNumber,versionNumber:input.version.versionNumber,pageNumber:index+1,pageCount});pdf.page.margins.bottom=bottomMargin;}
 pdf.end();return {buffer:await done,fileName:`NavStreet-SC-${input.offer.referenceNumber}-v${input.version.versionNumber}.pdf`,pageCount};
}
